# Generated by Django 5.2.1 on 2025-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0011_alter_customerloan_id_alter_loancategory_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='year',
            new_name='duration_value',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='duration_type',
            field=models.CharField(choices=[('years', 'Years'), ('months', 'Months')], default='years', max_length=10),
        ),
    ]
