# Generated by Django 5.2.1 on 2025-05-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0012_rename_year_loanrequest_duration_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='collateral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
