# Generated by Django 5.2.1 on 2025-05-21 17:04

import loginApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_alter_customersignup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='address',
            field=models.CharField(blank=True, default='Manila, Philippines', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customersignup',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customersignup',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customersignup',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customersignup',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customersignup',
            name='profile_picture',
            field=models.ImageField(blank=True, default=loginApp.models.get_default_profile_pic, null=True, upload_to='profile_pic'),
        ),
    ]
